default:
  image: ruby:3.1.2

before_script:
  - gem install bundler -N
  - bundle install --jobs $(nproc) "${FLAGS[@]}"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

test:
  script:
    - export CC_TEST_REPORTER_ID=b056b845823e1f34af9e77d46615b7425dadcaa6e9179b2d3940901a7c428984
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - bundle exec rake
    - ./cc-test-reporter after-build
