AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1.1
  NewCops: disable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'
